---

- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - spotify

  roles:
    - profile-gopro
  
  vars:
    - computername: mbr-30674
    - git_user_name: Antonia Kwok
    - git_user_email: akwok@gopro.com
