---

- name: install cask applications for all users
  homebrew_cask: name={{item}} state=present
  with_items:
    - hipchat
    - google-drive
    - keepingyouawake
    - boot2docker
    - firefox
    - iterm2
    - mou
    - sublime-text
    - shiftit
    - java

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - brew-cask
    - cassandra
    - elasticsearch
    - git
    - node
    - nginx
    - postgresql
    - redis
    - rhino
    - selenium-server-standalone

- name: check for gvm
  register: isGvmInstalled
  command: gvm list
  ignore_errors: True

- name: download gvm
  when: isGvmInstalled|failed
  get_url:
    url: https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer
    dest: /tmp/gvm-install.sh
    mode: 0440

- name: install gvm
  when: isGvmInstalled|failed
  command: bash /tmp/gvm-install.sh

- name: install go1.4.3
  command: gvm install go1.4.3

- name: setting path
  sudo: no
  action: shell source /Users/{{ansible_user_id}}/.gvm/scripts/gvm
